const typeActions = {
    BOOK_MESSAGE_ERROR: 'BOOK_MESSAGE_ERROR',
    BOOK_LOAD: 'BOOK_LOAD',
    BOOK_CREATE: 'BOOK_CREATE',
    BOOK_UPDATE: 'BOOK_UPDATE',
    BOOK_DELETE: 'BOOK_DELETE',
    BOOK_MESSAGE_SUCCESS: 'BOOK_MESSAGE_SUCCESS',
};

export default typeActions;